export let CONFIG = { 
    TIME_DEFAULTPLAYING: 300,
    TIME_DEFAULTRANDOM: 10,
    TIME_MINDURATION: 1,
    TIME_MAXDURATION: 20,
    MUSIC_DEFAULT: "/assets/audio/main.flac",
    ROUTER_PLAYER: "/player/",
    ROUTING_PARAMPLAYER_PLAYTIME: "playTime",
    ROUTING_PARAMPLAYER_RANDOMTIME: "randomTime",
    LANGUAGE_SPANISH: "es",
    LANGUAGE_DEFAULT: "en",
    KEY_HELP_MESSAGES: 'HELP_MESSAGES'
};